#!/bin/bash 
name=$1
if [ -z $name ]; then
	echo "No dir name"
else  
	if [ -f "$name" ]; then
		creat_dir
	else 
		echo "The file exits: "$name""
	fi
fi

creat_dir() {
	echo "Creat dir name: $name"
	mkdir $name
}
is_exits() {
	file_name=$1
	file_type=$2
	if [ -z $file_name ]; then
		echo "No "$file_type" name"
		return -1
	else  
		if [ -f "$file_name" ]; then
			#creat_dir
			return 0
		else 
			echo "The file exits: "$file_name""
			return -1
		fi
	fi

}
