#!/bin/bash 

#########################################
#########		Function		#########
#########################################
creat_dir() {
	dir_name=$1
	echo "Creat dir name: $dir_name"
	mkdir $dir_name
}

is_exits() {
	file_name=$1
	file_type=$2
	if [ -z $file_name ]; then
		echo "No "$file_type" name"
		return -1
	else  
		if [ -f $file_name ]; then
			echo "The file exits: "$file_name""
			return -1
		else 
			creat_dir "$file_name"
			return 0
		fi
	fi

}

#########################################
#########		  Main  		#########
#########################################
name=$1
is_exits "$name"
#if [ -z $name ]; then
#	echo "No dir name"
#else  
#	if [ -f "$name" ]; then
#		creat_dir
#	else 
#		echo "The file exits: "$name""
#	fi
#fi




